### ISSUE TITLE
More record update syntax

### ISSUE THREAD

**Issue by ndmitchell** [ndmitchell/record-dot-preprocessor#1]
`foo{x}` should be `foo{x=x}`.

**Comment by ndmitchell** [comment]
Note that it also works for `foo{x.b}`. Question if that should be `foo{x.b = x.b}` or `foo{b = x.b}` ?

**Comment by sofus-da** [comment]
My preference is `foo{b = x.b}`

**Comment by ndmitchell** [comment]
Note that this could also work for `Foo{x.b}` becoming `Foo{b=x.b}`, for consistency.

**Comment by sofus-da** [comment]
Agreed. That would be my (naive) expectation.

**Comment by ndmitchell** [comment]
Decisions:

* `foo{x} ==> foo{x=x}`
* `foo{x.b} ==> foo{b=x.b}`
* `Foo{x.b} ==> Foo{b=x.b}`

**Comment by ndmitchell** [comment]
I have implemented all but the `Foo` form.

**Comment by ndmitchell** [comment]
I'm leaving the `Foo` form for #11
