### ISSUE TITLE
Preprocessor breaks when trying to update usual records

### ISSUE THREAD

**Issue by DoctorRyner** [ndmitchell/record-dot-preprocessor#24]
<img width="1440" alt="Screenshot 2019-10-30 at 1 25 15 PM" src="https://user-images.githubusercontent.com/24430919/67850236-0d747180-fb19-11e9-9461-6441293c711f.png">

There is a workaround, I can enable it with pragma in each file where I use it and divide code that uses preprocessor but it's not that convenient at all

**Comment by DoctorRyner** [comment]
For example, that is valid
<img width="637" alt="Screenshot 2019-10-31 at 4 23 29 PM" src="https://user-images.githubusercontent.com/24430919/67950574-e5f5d580-fbfa-11e9-87cc-a2c2b27dc646.png">

But that is not, I can't use update syntax for record that wasn't compiled with record-dot-preprocessor
<img width="742" alt="Screenshot 2019-10-31 at 4 23 12 PM" src="https://user-images.githubusercontent.com/24430919/67950639-07ef5800-fbfb-11e9-8b39-034d7f6b3bbd.png">

**Comment by ndmitchell** [comment]
Note from the user manual at https://github.com/ndmitchell/record-dot-preprocessor#how-do-i-use-this-magic:

> You must make sure that the OPTIONS_GHC is applied both to the file where your records are defined, and where the record syntax is used

Does that answer your question? Unfortunately it's a fundamental limitation of this technique until after GHC gets support for deriving these instances itself (which is coming in a future GHC).

**Comment by DoctorRyner** [comment]
Not exactly, because it's also a native syntax to update a record, but ok, I get it, I will divide my code into parts that uses only records made with record-dot-preprocessor and that doesn't use it at all

**Comment by ndmitchell** [comment]
One option would be to write the necessary instances to get update working via hand. Unfortunately, they would be orphan instances.
