### ISSUE TITLE
Support update with a function

### ISSUE THREAD

**Issue by pkapustin** [ndmitchell/record-dot-preprocessor#27]
It would be nice to support update with a function as a more general version of update with an operator.

`expr{lbl <- f}` is equivalent to `expr{lbl = f expr.lbl}`, where f is a function.

I am not sure what the ideal syntax would be. Frege uses `<-`, Idris uses `$=`.

**Comment by ndmitchell** [comment]
The GHC proposal at https://github.com/ghc-proposals/ghc-proposals/pull/282 doesn't have that feature, so I don't plan on adding it to this library. The aim is to increasingly mirror that proposal, so I'm not going to add features that go further, and if I was to refactor the operator or punning pieces I'd remove them. If people want a long-term record preprocessor which has more stuff in it than that proposal, I suggest forking this repo (it's a perfectly valid thing to want, but I don't see myself using it, so wouldn't want to maintain it).

That said, `expr{lbl & f}` does what you want already.

**Comment by pkapustin** [comment]
Thanks, of course it does! :)

I agree that keeping the library close to the proposal is a good idea, but I think that it is also nice to keep already implemented features, as experience with them may help to develop future proposals.
