### ISSUE TITLE
GHC 8.10.2 incompatibility with preprocessor plugin

### ISSUE THREAD

**Issue by Dessix** [ndmitchell/record-dot-preprocessor#35]
The following line from the RIO quickstart fails on GHC `8.10.2` but builds just fine on `8.10.1`. 
```haskell
data Options = Options { optionsVerbose :: Bool }
```

This seems to happen with all records; the failures `8.10.2` produces with the plugin enabled look like this:
```
    • Illegal instance declaration for
        ‘GHC.Records.Extra.HasField "optionsVerbose" Options aplg’
        The coverage condition fails in class ‘GHC.Records.Extra.HasField’
          for functional dependency: ‘x r -> a’
        Reason: lhs types ‘"optionsVerbose"’, ‘Options’
          do not jointly determine rhs type ‘aplg’
        Un-determined variable: aplg
        Using UndecidableInstances might help
    • In the instance declaration for
        ‘GHC.Records.Extra.HasField "optionsVerbose" Options aplg’
```

**Comment by ndmitchell** [comment]
Are you using the same version of record-dot-preprocessor in both versions of GHC? The latest version requires the extensions listed at https://github.com/ndmitchell/record-dot-preprocessor#how-do-i-use-this-magic, which includes turning on `UndecidableInstances`. My suspicion is you are using the older version with the older GHC.

**Comment by Dessix** [comment]
Ah- that’d do it. What changed to make undecidables necessary? Unless I’m mistaken, they’re a bit iffy to enable at all, let alone across the entire codebase?

**Comment by ndmitchell** [comment]
Records containing type families - see #29 - require undecidable instances. They can be iffy in places, and I wouldn't want them to be a long-term solution, but the whole record-dot-preprocessor thing is meant to be a stopgap to real compiler support. It would be possible to have two plugin modules, one with undecidable and one without, if it mattered enough to people.

**Comment by Dessix** [comment]
Was this type families constraint introduced in 8.10.2? My types didn’t change, as far as I’m aware, and I don’t think a boolean is a type family?

**Comment by ndmitchell** [comment]
It was introduced in record-dot-preprocessor 0.2.7. I imagine you have 0.2.6 installed on GHC 8.10.1.

It isn't a type family, but we moved to a desugaring that allows type families (before they would fail), but unfortunately requires that extension.

**Comment by neongreen** [comment]
This change was done in https://github.com/ndmitchell/record-dot-preprocessor/pull/34.
